version: '3.9'

services:
  nginx_proxy:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./blazorproxy.conf:/etc/nginx/nginx.conf

  blazor_app:
    build: 
      context: ./DockerWasm
    ports:
      - '8080:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080

  kapa_dev:
    build: 
      context: ./kapa-dot-dev-v2
    ports:
      - '3000:3000'

