version: '3.9'

services:
  blazor_app:
    build: 
      context: ./DockerWasm

  kapa_dev:
    build: 
      context: ./kapa-dot-dev-v2
    ports:
      - '80:80'
    volumes:
      - ./blazorproxy.conf:/etc/nginx/nginx.conf

